/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import java.awt.event.ActionEvent;


/**
 *
 * @author Bruno
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH); // Comando para inicializar com tela inteira

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        labelHoraSistema = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        labelNomeUsuario = new javax.swing.JLabel();
        labelCargoUsuario = new javax.swing.JLabel();
        labelNivelAcesso = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        MenuCadHospede = new javax.swing.JMenuItem();
        MenuConHospede = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        MenuCadQuarto = new javax.swing.JMenuItem();
        MenuConQuarto = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        MenuCadFuncionario = new javax.swing.JMenuItem();
        MenuConFuncionario = new javax.swing.JMenuItem();
        jMenu11 = new javax.swing.JMenu();
        MenuCadFornecedor = new javax.swing.JMenuItem();
        MenuConFornecedor = new javax.swing.JMenuItem();
        jMenu12 = new javax.swing.JMenu();
        MenuCadProdutos = new javax.swing.JMenuItem();
        MenuConProdutos = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        MenuCadReserva = new javax.swing.JMenuItem();
        MenuConReserva = new javax.swing.JMenuItem();
        MenuFinReserva = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        MenuConsumoProdutos = new javax.swing.JMenuItem();
        MenuConsumoServicos = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        MenuCadContasPagar = new javax.swing.JMenuItem();
        MenuConContasPagar = new javax.swing.JMenuItem();
        jMenu13 = new javax.swing.JMenu();
        MenuCadContasReceber = new javax.swing.JMenuItem();
        MenuConContasReceber = new javax.swing.JMenuItem();
        MenuBalanco = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenu14 = new javax.swing.JMenu();
        MenuRelContasPagar = new javax.swing.JMenuItem();
        MenuRelContasReceber = new javax.swing.JMenuItem();
        MenuRelBalaco = new javax.swing.JMenuItem();
        jMenu15 = new javax.swing.JMenu();
        MenuRelQuartosDisp = new javax.swing.JMenuItem();
        MenuRelQuartosOcup = new javax.swing.JMenuItem();
        MenuRelReservasFuturas = new javax.swing.JMenuItem();
        jMenu16 = new javax.swing.JMenu();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenuItem19 = new javax.swing.JMenuItem();
        MenuRelHospedes = new javax.swing.JMenuItem();
        MenuRelFuncionarios = new javax.swing.JMenuItem();
        MenuRelFornecedores = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        MenuFazerBackup = new javax.swing.JMenuItem();
        MenuRestaurarBackup = new javax.swing.JMenuItem();
        MenuSair = new javax.swing.JMenu();

        jMenuItem3.setText("jMenuItem3");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem7.setText("jMenuItem7");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pousada JAVA");
        setUndecorated(true);
        setSize(new java.awt.Dimension(1200, 600));

        jPanel1.setPreferredSize(new java.awt.Dimension(1058, 50));

        jLabel1.setBackground(new java.awt.Color(255, 255, 204));
        jLabel1.setFont(new java.awt.Font("Yu Gothic Medium", 3, 14)); // NOI18N
        jLabel1.setText("Sistema Hotel  - Sistema Desenvolvido por Bruno Carvalho - Todos os Direitos Rservado - 2024");
        jLabel1.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(15, 15, 15))
        );

        jScrollPane1.setBorder(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/LOGO.jpg"))); // NOI18N

        labelHoraSistema.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        labelHoraSistema.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelHoraSistema.setText("Horário do Sistema");
        labelHoraSistema.setToolTipText("");
        labelHoraSistema.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Usuário:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Cargo:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Nível Acesso:");

        labelNomeUsuario.setFont(new java.awt.Font("Segoe UI Historic", 3, 14)); // NOI18N
        labelNomeUsuario.setText("Nome");

        labelCargoUsuario.setFont(new java.awt.Font("Segoe UI Historic", 3, 14)); // NOI18N
        labelCargoUsuario.setText("text");

        labelNivelAcesso.setFont(new java.awt.Font("Segoe UI Historic", 3, 14)); // NOI18N
        labelNivelAcesso.setText("text");

        jButton1.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/IconsPrincipal/IconBtnLogout.png"))); // NOI18N
        jButton1.setText("Logout");
        jButton1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 255, 255)));
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jSeparator3)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelCargoUsuario)
                            .addComponent(labelNivelAcesso)
                            .addComponent(labelNomeUsuario)))
                    .addComponent(jLabel4))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(116, 116, 116))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelHoraSistema, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelHoraSistema)
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(labelNomeUsuario))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(labelCargoUsuario))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(labelNivelAcesso))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jScrollPane1.setViewportView(jPanel2);

        jDesktopPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 726, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/IconsPrincipal/IconCadastro.png"))); // NOI18N
        jMenu1.setText("Cadastro    |");

        jMenu8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/IconsPrincipal/IconHospede.png"))); // NOI18N
        jMenu8.setText("Hospedes");

        MenuCadHospede.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/IconsPrincipal/IconHospedeCadastro.png"))); // NOI18N
        MenuCadHospede.setText("Cadastrar");
        jMenu8.add(MenuCadHospede);

        MenuConHospede.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/IconsPrincipal/IconHospedeConsulta.png"))); // NOI18N
        MenuConHospede.setText("Consultar");
        jMenu8.add(MenuConHospede);

        jMenu1.add(jMenu8);

        jMenu9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/IconsPrincipal/IconQuarto.png"))); // NOI18N
        jMenu9.setText("Quartos");

        MenuCadQuarto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/IconsPrincipal/IconQuartoCadastro.png"))); // NOI18N
        MenuCadQuarto.setText("Cadastrar");
        jMenu9.add(MenuCadQuarto);

        MenuConQuarto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/IconsPrincipal/IconQuartoConsulta.png"))); // NOI18N
        MenuConQuarto.setText("Consultar");
        jMenu9.add(MenuConQuarto);

        jMenu1.add(jMenu9);

        jMenu10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/IconsPrincipal/IconFuncionarios.png"))); // NOI18N
        jMenu10.setText("Funcionarios");

        MenuCadFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/IconsPrincipal/IconFuncionarioCadastro.png"))); // NOI18N
        MenuCadFuncionario.setText("Cadastro");
        jMenu10.add(MenuCadFuncionario);

        MenuConFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/IconsPrincipal/IconFuncionarioConsulta.png"))); // NOI18N
        MenuConFuncionario.setText("Consulta");
        MenuConFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuConFuncionarioActionPerformed(evt);
            }
        });
        jMenu10.add(MenuConFuncionario);

        jMenu1.add(jMenu10);

        jMenu11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/IconsPrincipal/IconFornecedor.png"))); // NOI18N
        jMenu11.setText("Fornecedores");

        MenuCadFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/IconsPrincipal/IconFornecedorCadastro.png"))); // NOI18N
        MenuCadFornecedor.setText("Cadastro");
        jMenu11.add(MenuCadFornecedor);

        MenuConFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/IconsPrincipal/IconFornecedoroConsulta.png"))); // NOI18N
        MenuConFornecedor.setText("Consulta");
        jMenu11.add(MenuConFornecedor);

        jMenu1.add(jMenu11);

        jMenu12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/IconsPrincipal/IconProduto.png"))); // NOI18N
        jMenu12.setText("Produtos");

        MenuCadProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/IconsPrincipal/IconProdutoCadastro.png"))); // NOI18N
        MenuCadProdutos.setText("Cadastro");
        jMenu12.add(MenuCadProdutos);

        MenuConProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/IconsPrincipal/IconProdutosConsulta.png"))); // NOI18N
        MenuConProdutos.setText("Consulta");
        jMenu12.add(MenuConProdutos);

        jMenu1.add(jMenu12);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/IconsPrincipal/IconReserva.png"))); // NOI18N
        jMenu2.setText("Reservas    |");

        MenuCadReserva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/IconsPrincipal/IconReservaCadastro.png"))); // NOI18N
        MenuCadReserva.setText("Cadastro Reserva");
        jMenu2.add(MenuCadReserva);

        MenuConReserva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/IconsPrincipal/IconReservaConsulta.png"))); // NOI18N
        MenuConReserva.setText("Consulta Reserva");
        jMenu2.add(MenuConReserva);

        MenuFinReserva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/IconsPrincipal/IconReservaFinalizar.png"))); // NOI18N
        MenuFinReserva.setText("Finalizar Reserva");
        MenuFinReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuFinReservaActionPerformed(evt);
            }
        });
        jMenu2.add(MenuFinReserva);

        jMenuBar1.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/IconsPrincipal/IconConsumo.png"))); // NOI18N
        jMenu3.setText("Consumo    |");

        MenuConsumoProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/IconsPrincipal/IconConsumoProdutos.png"))); // NOI18N
        MenuConsumoProdutos.setText("Produtos");
        jMenu3.add(MenuConsumoProdutos);

        MenuConsumoServicos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/IconsPrincipal/IconConsumoServico.png"))); // NOI18N
        MenuConsumoServicos.setText("Serviços");
        jMenu3.add(MenuConsumoServicos);

        jMenuBar1.add(jMenu3);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/IconsPrincipal/iconFinanceiro.png"))); // NOI18N
        jMenu4.setText("Financeiro    |");

        jMenu7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/IconsPrincipal/IconFinanceiroContasPagar.png"))); // NOI18N
        jMenu7.setText("Contas a Pagar");

        MenuCadContasPagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/IconsPrincipal/IconCadastro.png"))); // NOI18N
        MenuCadContasPagar.setText("Cadastro");
        jMenu7.add(MenuCadContasPagar);

        MenuConContasPagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/IconsPrincipal/IconConsulta.png"))); // NOI18N
        MenuConContasPagar.setText("Consulta");
        jMenu7.add(MenuConContasPagar);

        jMenu4.add(jMenu7);

        jMenu13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/IconsPrincipal/IconFinanceiroContasReceber.png"))); // NOI18N
        jMenu13.setText("Contas a Receber");

        MenuCadContasReceber.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/IconsPrincipal/IconCadastro.png"))); // NOI18N
        MenuCadContasReceber.setText("Cadastro");
        jMenu13.add(MenuCadContasReceber);

        MenuConContasReceber.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/IconsPrincipal/IconConsulta.png"))); // NOI18N
        MenuConContasReceber.setText("Consulta");
        jMenu13.add(MenuConContasReceber);

        jMenu4.add(jMenu13);

        MenuBalanco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/IconsPrincipal/IconFinanceiroBalanco.png"))); // NOI18N
        MenuBalanco.setText("Balanço");
        jMenu4.add(MenuBalanco);

        jMenuBar1.add(jMenu4);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/IconsPrincipal/IconRelatorio.png"))); // NOI18N
        jMenu5.setText("Relatórios    |");

        jMenu14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/IconsPrincipal/IconRelMenu.png"))); // NOI18N
        jMenu14.setText("Financeiro");

        MenuRelContasPagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/IconsPrincipal/IconRelRelatorios.png"))); // NOI18N
        MenuRelContasPagar.setText("Contas a Pagar");
        jMenu14.add(MenuRelContasPagar);

        MenuRelContasReceber.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/IconsPrincipal/IconRelRelatorios.png"))); // NOI18N
        MenuRelContasReceber.setText("Contas a Receber");
        jMenu14.add(MenuRelContasReceber);

        MenuRelBalaco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/IconsPrincipal/IconRelRelatorios.png"))); // NOI18N
        MenuRelBalaco.setText("Balaço");
        jMenu14.add(MenuRelBalaco);

        jMenu5.add(jMenu14);

        jMenu15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/IconsPrincipal/IconRelMenu.png"))); // NOI18N
        jMenu15.setText("Reservas");

        MenuRelQuartosDisp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/IconsPrincipal/IconRelRelatorios.png"))); // NOI18N
        MenuRelQuartosDisp.setText("Quartos Disponíveis");
        jMenu15.add(MenuRelQuartosDisp);

        MenuRelQuartosOcup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/IconsPrincipal/IconRelRelatorios.png"))); // NOI18N
        MenuRelQuartosOcup.setText("Quartos Ocupados");
        jMenu15.add(MenuRelQuartosOcup);

        MenuRelReservasFuturas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/IconsPrincipal/IconRelRelatorios.png"))); // NOI18N
        MenuRelReservasFuturas.setText("Reservas Futuras");
        jMenu15.add(MenuRelReservasFuturas);

        jMenu5.add(jMenu15);

        jMenu16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/IconsPrincipal/IconRelMenu.png"))); // NOI18N
        jMenu16.setText("Vendas");

        jMenuItem18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/IconsPrincipal/IconRelRelatorios.png"))); // NOI18N
        jMenuItem18.setText("Itens Vendidos");
        jMenu16.add(jMenuItem18);

        jMenuItem19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/IconsPrincipal/IconRelRelatorios.png"))); // NOI18N
        jMenuItem19.setText("Serviços Vendidos");
        jMenu16.add(jMenuItem19);

        jMenu5.add(jMenu16);

        MenuRelHospedes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/IconsPrincipal/IconRelRelatorios.png"))); // NOI18N
        MenuRelHospedes.setText("Hospedes");
        jMenu5.add(MenuRelHospedes);

        MenuRelFuncionarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/IconsPrincipal/IconRelRelatorios.png"))); // NOI18N
        MenuRelFuncionarios.setText("Funcionários");
        jMenu5.add(MenuRelFuncionarios);

        MenuRelFornecedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/IconsPrincipal/IconRelRelatorios.png"))); // NOI18N
        MenuRelFornecedores.setText("Fornecedores");
        jMenu5.add(MenuRelFornecedores);

        jMenuBar1.add(jMenu5);

        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/IconsPrincipal/IconSeguranca.png"))); // NOI18N
        jMenu6.setText("Segurança    |");

        MenuFazerBackup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/IconsPrincipal/IconSegurancaFazerBackup.png"))); // NOI18N
        MenuFazerBackup.setText("Fazer Backup");
        jMenu6.add(MenuFazerBackup);

        MenuRestaurarBackup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/IconsPrincipal/IconSegurancaRestaurarBackup.png"))); // NOI18N
        MenuRestaurarBackup.setText("Restaurar Backup");
        jMenu6.add(MenuRestaurarBackup);

        jMenuBar1.add(jMenu6);

        MenuSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/IconsPrincipal/IconSair.png"))); // NOI18N
        MenuSair.setText("Sair    |");
        MenuSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuSairMouseClicked(evt);
            }
        });
        MenuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuSairActionPerformed(evt);
            }
        });
        jMenuBar1.add(MenuSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jDesktopPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MenuSairActionPerformed(ActionEvent evt) {//GEN-FIRST:event_MenuSairActionPerformed
        
    }//GEN-LAST:event_MenuSairActionPerformed

    private void MenuConFuncionarioActionPerformed(ActionEvent evt) {//GEN-FIRST:event_MenuConFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuConFuncionarioActionPerformed

    private void MenuFinReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuFinReservaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuFinReservaActionPerformed

    private void MenuSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuSairMouseClicked
        //fechar tela principal
        dispose();
    }//GEN-LAST:event_MenuSairMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        TelaLogin telaLogin = new TelaLogin();
        //Fechar sistema
        dispose();
        telaLogin.setVisible(true);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuBalanco;
    private javax.swing.JMenuItem MenuCadContasPagar;
    private javax.swing.JMenuItem MenuCadContasReceber;
    private javax.swing.JMenuItem MenuCadFornecedor;
    private javax.swing.JMenuItem MenuCadFuncionario;
    private javax.swing.JMenuItem MenuCadHospede;
    private javax.swing.JMenuItem MenuCadProdutos;
    private javax.swing.JMenuItem MenuCadQuarto;
    private javax.swing.JMenuItem MenuCadReserva;
    private javax.swing.JMenuItem MenuConContasPagar;
    private javax.swing.JMenuItem MenuConContasReceber;
    private javax.swing.JMenuItem MenuConFornecedor;
    private javax.swing.JMenuItem MenuConFuncionario;
    private javax.swing.JMenuItem MenuConHospede;
    private javax.swing.JMenuItem MenuConProdutos;
    private javax.swing.JMenuItem MenuConQuarto;
    private javax.swing.JMenuItem MenuConReserva;
    private javax.swing.JMenuItem MenuConsumoProdutos;
    private javax.swing.JMenuItem MenuConsumoServicos;
    private javax.swing.JMenuItem MenuFazerBackup;
    private javax.swing.JMenuItem MenuFinReserva;
    private javax.swing.JMenuItem MenuRelBalaco;
    private javax.swing.JMenuItem MenuRelContasPagar;
    private javax.swing.JMenuItem MenuRelContasReceber;
    private javax.swing.JMenuItem MenuRelFornecedores;
    private javax.swing.JMenuItem MenuRelFuncionarios;
    private javax.swing.JMenuItem MenuRelHospedes;
    private javax.swing.JMenuItem MenuRelQuartosDisp;
    private javax.swing.JMenuItem MenuRelQuartosOcup;
    private javax.swing.JMenuItem MenuRelReservasFuturas;
    private javax.swing.JMenuItem MenuRestaurarBackup;
    private javax.swing.JMenu MenuSair;
    private javax.swing.JButton jButton1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu14;
    private javax.swing.JMenu jMenu15;
    private javax.swing.JMenu jMenu16;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel labelCargoUsuario;
    private javax.swing.JLabel labelHoraSistema;
    private javax.swing.JLabel labelNivelAcesso;
    private javax.swing.JLabel labelNomeUsuario;
    // End of variables declaration//GEN-END:variables
}
